export const ACTION_TYPES = {
    GAMES_DATA_LOADING: 'GAMES_DATA_LOADING',
    SET_GAMES_DATA: 'SET_GAMES_DATA',
    TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
    SET_FAVORITES: 'SET_FAVORITES',
    SET_FAVORITES_DATA: 'SET_FAVORITES_DATA',
    SET_SEARCHED_DATA: 'SET_SEARCHED_DATA'
}